---
title: "Homework 6"
author: "Beibei Cao"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa, AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```


Start with one city.

```{r}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")

glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```


Try this across cities.

```{r}
models_results_df = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

```{r}
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```



## Problem 2

Load and clean data.

```{r}
baby_df = 
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>%
  filter(frace != 9 & mrace != 8) %>% 
  drop_na() %>% 
  mutate(
    babysex = case_when(
      babysex == 1 ~ "male",
      babysex == 2 ~ "female"
    ),
    frace = case_when(
      frace == 1 ~ "White",
      frace == 2 ~ "Black",
      frace == 3 ~ "Asian",
      frace == 4 ~ "Puerto Rican",
      frace == 8 ~ "Other"
    ),
    mrace = case_when(
      mrace == 1 ~ "White",
      mrace == 2 ~ "Black",
      mrace == 3 ~ "Asian",
      mrace == 4 ~ "Puerto Rican",
      mrace == 8 ~ "Other"
    ),
    malform = case_when(
      malform == 0 ~ "absent",
      malform == 1 ~ "present"
    ),
    across(where(is.character), as.factor)
    )
```

#### Modeling 

###### Model 1: my choice

```{r}
# fit all variables
mul_fit = lm(bwt ~ ., data = baby_df)
summary(mul_fit)
```

```{r}
# use step-wide backward method to select variables based on lowest AIC values 
# step(mul_fit, direction = "backward") 

# this is the summery of the last step of the `step()`, check how this fit
summary(lm(formula = bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + mrace + parity + ppwt + smoken, data = baby_df))
```

```{r}
# finally select variables with the most significant p-values according to the regression statistics above
fit_df =
  baby_df %>% select(bwt, babysex, bhead, blength, delwt, gaweeks, mheight, ppwt, smoken)

# check regression dtatistics 
model_1 = lm(bwt ~ ., data = fit_df)
summary(model_1)
```

```{r}
model_1 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```


Check residuals.
```{r}
fit_df %>% 
  modelr::add_residuals(model_1) %>% 
  modelr::add_predictions(model_1) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.3) +
  labs(
    title = "Predictor vs. Residual",
    x = "Predictor",
    y = "Residual"
  )
```

```{r include=FALSE}
fit_df %>% 
  modelr::add_residuals(model_1) %>% 
  ggplot(aes(x = resid)) +
  geom_density() +
  labs(
    title = "Residual Destribution",
    x = "Residual",
    y = "Density"
  )
```

###### Model 2: Length at birth and gestational age as predictors (main effectes only)

```{r}
model_2 = lm(bwt ~ blength + gaweeks, data = baby_df)

model_2 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```

###### Model 3: Head circumference, length, sex and all interactions between these

```{r}
model_3 = lm(bwt ~ bhead * blength * babysex, data = baby_df)

model_3 %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable()
```

```{r}
cv_df = 
  crossv_mc(baby_df, 100) %>% 
   mutate(
        train = map(train, as.tibble),
        test = map(test, as.tibble)
    )
```

###### Cross Validation

```{r}
cv_res = 
  cv_df %>% 
    mutate(
        model_1 = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + 
                                   gaweeks + mheight + ppwt + smoken, data = .x)),
        model_2 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
        model_3 = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))
    ) %>% 
    mutate(
        rmse_model_1 = 
          map2_dbl(model_1, test, ~rmse(model = .x, data = .y)),
        rmse_model_2 = 
          map2_dbl(model_2, test, ~rmse(model = .x, data = .y)),
        rmse_medel_3 = 
          map2_dbl(model_3, test, ~rmse(model = .x, data = .y))
    )
```

```{r}
cv_res %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_violin() 
```






